---
- hosts: webserver
  become: true
  tasks:
    - name: Install apache2
      apt: name=apache2 state=latest
- hosts: db
  become: true
  tasks:
    - name: Install mysql
      apt: name=mysql-server state=latest
